// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIyu9LXku2xodTuRbOdz59VaODrT_soF0',
    appId: '1:37746749583:web:881d8b5f36b81a978240fa',
    messagingSenderId: '37746749583',
    projectId: 'fir-lecture1-b0026',
    authDomain: 'fir-lecture1-b0026.firebaseapp.com',
    storageBucket: 'fir-lecture1-b0026.firebasestorage.app',
    measurementId: 'G-J9PWN4PR1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY0I1SM-rUMCz4Up_qRCCet1C_E3LnSVo',
    appId: '1:37746749583:android:ca2edc57c59dd3e78240fa',
    messagingSenderId: '37746749583',
    projectId: 'fir-lecture1-b0026',
    storageBucket: 'fir-lecture1-b0026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbjHPhfxOpVLksl2BllBixsJz9wCGGevk',
    appId: '1:37746749583:ios:9bc921fc2374fe618240fa',
    messagingSenderId: '37746749583',
    projectId: 'fir-lecture1-b0026',
    storageBucket: 'fir-lecture1-b0026.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbjHPhfxOpVLksl2BllBixsJz9wCGGevk',
    appId: '1:37746749583:ios:9bc921fc2374fe618240fa',
    messagingSenderId: '37746749583',
    projectId: 'fir-lecture1-b0026',
    storageBucket: 'fir-lecture1-b0026.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIyu9LXku2xodTuRbOdz59VaODrT_soF0',
    appId: '1:37746749583:web:db55964793ba0d3a8240fa',
    messagingSenderId: '37746749583',
    projectId: 'fir-lecture1-b0026',
    authDomain: 'fir-lecture1-b0026.firebaseapp.com',
    storageBucket: 'fir-lecture1-b0026.firebasestorage.app',
    measurementId: 'G-MVXW5GW8ZT',
  );
}
